# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-app-prod"
  description: "kubrix-johnny-app-prod"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-app-prod.demo.kubrix.cloud
      title: Prod Instance of kubrix-johnny-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-johnny-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-app-prod'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-app-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-johnny-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-app-prod&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "kubrix"
  system: johnny-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-app
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-app-qa"
  description: "kubrix-johnny-app-qa"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-app-qa.demo.kubrix.cloud
      title: QA Instance of kubrix-johnny-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-johnny-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-app-qa'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-app-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-johnny-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-app-qa&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "kubrix"
  system: johnny-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-app
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-app-test"
  description: "kubrix-johnny-app-test"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://kubrix-johnny-app-test.demo.kubrix.cloud
      title: Test Instance of kubrix-johnny-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-johnny-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johnny-app-test'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: johnny-app-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-johnny-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=kubrix-johnny-app-test&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "kubrix"
  system: johnny-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: kubrix-johnny-app
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubrix-johnny-app"
  description: "kubrix-johnny-app"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: https://argocd.demo.kubrix.cloud/applications/adn-kubrix/kubrix-johnny-app?resource=
      title: ArgoCD Application Information of kubrix-johnny-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/kubrix-johnny-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kubrix-johnny-app'
    argocd/app-namespace: adn-kubrix
    argocd/app-name: kubrix-johnny-app
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/kubrix-johnny-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "kubrix"
  system: johnny-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
